# Week 1 

Q1 Write a NumPy program to create an array of all even integers from 30 to 70

In [1]:
import numpy as np

even_array = np.arange(30, 71, 2)
print("Array of even integers from 30 to 70:", even_array)

Array of even integers from 30 to 70: [30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


Q2 Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution.

In [3]:
random_array = np.random.randn(15)
print("Array of 15 random numbers from standard normal distribution:", random_array)

Array of 15 random numbers from standard normal distribution: [ 0.59033846 -0.35692738 -1.23126324 -0.08763887 -1.01954533 -0.86970005
  0.67924714  0.54759316 -0.65197688 -0.230995    0.20444346 -0.35787572
 -0.84114058  0.27042826  1.01495567]


Q3 How to compute the cross-product of two matrices in NumPy?

In [4]:
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

cross_product = np.cross(matrix1, matrix2)
print("Cross-product of two matrices:")
print(cross_product)

Cross-product of two matrices:
[-4 -4]


Q4 How to compute the determinant of an array using NumPy?

In [5]:
array = np.array([[1, 2], [3, 4]])

determinant = np.linalg.det(array)
print("Determinant of the array:", determinant)

Determinant of the array: -2.0000000000000004


Q5 How to create a 3x3x3 array with random values using NumPy?

In [6]:
random_3d_array = np.random.random((3, 3, 3))
print("3x3x3 array with random values:")
print(random_3d_array)

3x3x3 array with random values:
[[[0.40191902 0.84288072 0.57812471]
  [0.18172717 0.07575278 0.72123225]
  [0.45306344 0.12709105 0.57126532]]

 [[0.131821   0.6678937  0.11935729]
  [0.29617552 0.36328269 0.76659831]
  [0.23640703 0.74966587 0.42025609]]

 [[0.47926511 0.2339371  0.23638538]
  [0.80909051 0.65161999 0.35433669]
  [0.74420046 0.57826841 0.15458392]]]


Q6 How to create a 5x5 array with random values and find the minimum and maximum values using NumPy?

In [7]:
random_5x5_array = np.random.random((5, 5))
print("5x5 array with random values:")
print(random_5x5_array)

min_value = np.min(random_5x5_array)
max_value = np.max(random_5x5_array)
print("Minimum value:", min_value)
print("Maximum value:", max_value)

5x5 array with random values:
[[0.82692444 0.72498774 0.72848014 0.89292701 0.82202109]
 [0.52683113 0.07034929 0.6159188  0.21668592 0.80464444]
 [0.48096208 0.20713593 0.9826767  0.1276368  0.91474538]
 [0.15972502 0.20247754 0.56920982 0.4764766  0.69383286]
 [0.10012458 0.87175105 0.91988847 0.53979922 0.49440223]]
Minimum value: 0.07034928833478138
Maximum value: 0.9826767044053123


Q7 How to compute the mean, standard deviation, and variance of a given array along the second axis in NumPy?

In [8]:
array = np.array([[1, 2, 3], [4, 5, 6]])

mean = np.mean(array, axis=1)
std_deviation = np.std(array, axis=1)
variance = np.var(array, axis=1)

print("Mean along the second axis:", mean)
print("Standard deviation along the second axis:", std_deviation)
print("Variance along the second axis:", variance)

Mean along the second axis: [2. 5.]
Standard deviation along the second axis: [0.81649658 0.81649658]
Variance along the second axis: [0.66666667 0.66666667]
